### ISSUE TITLE
Скрипты

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#1]
https://github.com/polina-nn/news/blob/c6c0b6d15155c6c7a0bf7b33fa6046d6c6131182/_scripts/4_GetCategoryList.sh#L1

не работает

https://github.com/polina-nn/news/blob/c6c0b6d15155c6c7a0bf7b33fa6046d6c6131182/_scripts/5_AddOneNews.sh#L5
пути тоже нерабочие

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/1_scripts
Добрый день! Запускать скрипты из корневой папки "news"
