### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#11]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/Lib/Category/CategoryIO.hs#L93-L100

я так понимаю данная функция используется в цепочке вычислений. Почему бы здесь не использовать MonadError, чтобы избавиться от этой проверки здесь, и чтобы подобные функции выполняли то, что от них требуется без лишней логики.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/11_handle_errors
Здравствуй! 
Я видимо, что то не понимаю. Сделала с использованием Control.Monad.Trans.Except два эндпойта: AddOneUser.hs и AddOneImage.hs
В эндпойте AddOneImage.hs есть функция allCheck. В цепочке проверок только последняя функция создает новые данные, остальные функции это только проверки, возвращающие один тип ошибок и разные данные (которые нам не нужны).
Я протестировала у данного варианта работу с ошибками. Тестовые скрипты, выдающие ошибки, в папке - /_scripts_error.
У меня вопрос, что я делаю не так, раз у меня запрос 6_AddOneImageFileNotFound_400.sh отдает ошибку HTTP/1.1 500 Internal Server Error  ( как я понимаю сам сервант пишет в терминал ./_images/white_base645: openBinaryFile: does not exist (No such file or directory)). При этом в логах пишется  все как надо :
2023-02-17 13:21:53 [Debug] [Error] ERROR NotExistImageFile "checkImageFileExist: BAD!  File: does not exist (No such file or directory) ". Я раньше на этот запрос возвращала error 400

Конечно у меня еще был вариант, если функцию allCheck писать без 
checkAndDecodeBase64Image'' = do { checkUserAuthor'' >> checkImageFileExist' >> checkPngImage' >> checkAndDecodeBase64Image' } `EX.catchE` EX.throwE, а использовать только EX.runExceptT и возиться с case Either (но это очень нездорово выглядит) , allCheck работает правильно и на запрос 6_AddOneImageFileNotFound_400.sh  отдает 400 ошибку, как я и ожидаю.

Остальные эндпойты я не правила, так как видимо, что то я не то делаю. Подскажи мне, пожалуйста, что делать.

**Comment by pavelzarubin** [comment]
https://github.com/polina-nn/news/blob/cf0cab323fe01c85e603ea9b605e90cd12b5ad03/src/EndPoints/AddOneImage.hs#L63-L70

```
2023-02-17 13:46:40 [Debug] [Debug] checkUserAuthor: OK!
2023-02-17 13:46:40 [Debug] [Error] ERROR NotExistImageFile "checkImageFileExist: BAD!  File: does not exist (No such file or directory) "
2023-02-17 13:46:40 [Debug] [Debug] checkPngImage: OK!
./_images/white_base645: openBinaryFile: does not exist (No such file or directory)
```

**Comment by pavelzarubin** [comment]
ты делаешь как я понимаю последовательную проверку всего, что в принципе очень странно, но допустим.
По логам видно, проверка что пользователь автор прошла, проверка что файл существует не прошла.
А за ними идут еще проверки. Зачем???? Дальше я так понимаю проверяется формат, а потом ты несуществующий файл пытаешься открыть и декодировать. Вот тут и вылетает исключение, которое не обрабатывается и пробрасывается в сервант видимо. Ну он и не знает что с ним делать, потому и кидает 500.

**Comment by pavelzarubin** [comment]
Тебе не нужно выбрасывать первое попавшееся исключение сразу, а не доводить все проверки до конца.

**Comment by pavelzarubin** [comment]
```haskell
IO (EX.ExceptT ErrorTypes.AddImageError IO ImageDecodeBase64ByteString)
```
вот на это обрати внимание, подумай в какой монаде нужно действовать, и про лифты не забудь
