### ISSUE TITLE
FromMaybe

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#12]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/Lib/News/News.hs#L116-L122

здесь явно напрашивается использование `fromMaybe`. Можно создать переменную с датой по умолчанию, и вместо этих функций использовать ее и с fromMaybe.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/12_from_maybe
