### ISSUE TITLE
Имена функций

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#13]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/Lib/News/News.hs#L136-L138

что это и зачем оно нужно? Отрази это в имени функции. Вообще подобные названия недопустимы, проверь остальные модули на наличие подобных ошибок.

**Comment by pavelzarubin** [comment]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/DbServices.hs#L53-L66

имена начинающиеся с подчеркивания в функциях используются, как-будто мы их игнорируем.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/13_functions_names
