### ISSUE TITLE
Разный синтаксис

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#14]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/Lib/News/NewsIO.hs#L54

https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/Lib/News/NewsIO.hs#L47

Чем обусловлен разный синтаксис для запросов к базе данных? По-хорошему, для читаемости использовать что-то одно.

**Comment by polina-nn** [comment]
Привела запросы к одному синтаксису 
https://github.com/polina-nn/news/pull/new/14_SqlQQ_for_Requests
