### ISSUE TITLE
Использование расширений

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#15]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/AddOneCategory.hs#L76

зачем использовать `pack` когда включено расширение `OverloadedString`?

также ты можешь все подключенные расширение вынести в `package.yaml`, особенно если они используются практически везде

**Comment by pavelzarubin** [comment]
```haskell
T.concat [T.pack "All Check: BAD!  \n"]
```
тут вообще перестаралась

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/15_logging
1. Перенесла расширения в файл package.yaml
2.  Убрала где возможно, T.concat [T.pack...] , но для отображения в логах  кириллицы без функций из EndPoints.Lib.ToText не обойтись. 
3. При прогоне через hlint появляется Error: Parse error вызванная функциями библиотеки Database.PostgreSQL.Simple.SqlQQ (sql) . Отключила эти ошибки в .hlint.yaml, хотя правильно отключить именно ошибки из определенных функций конкретной библиотеки. Но это пока не получилось. Посмотрю настройки hlint еще раз позднее.
