### ISSUE TITLE
Уточнение типов

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#16]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/GetAuthorsNewsSearchList.hs#L81

Лишние уточнения типов. Присутствуют очень часто. Если не уверена что тип выводится, то лучше поставь hls и уточняй там где это действительно необходимо.

**Comment by polina-nn** [comment]
Добрый день! Вроде больше лишних выводов типов нет

**Comment by pavelzarubin** [comment]
закрывай
