### ISSUE TITLE
Лишние комментарии

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#17]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/EndPoints/GetOneImage.hs#L48

**Comment by polina-nn** [comment]
Убрала лишние

**Comment by pavelzarubin** [comment]
https://github.com/polina-nn/news/blob/0794d9a72960103d0b8e9d08ba9c104c75f07810/src/EndPoints/Lib/ToHttpResponse.hs#L22

это зачем?

**Comment by pavelzarubin** [comment]
https://github.com/polina-nn/news/blob/0794d9a72960103d0b8e9d08ba9c104c75f07810/src/Types/ErrorTypes.hs#L18

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/17_redundant_comments
