### ISSUE TITLE
HLINT

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#18]
В коде присутствуют ошибки, на которые реагирует hlint. 
```haskell
logWith :: Config -> Logger.Level -> T.Text -> IO ()
logWith сonf logLevel text = do
  let minLevel = confMinLevel сonf
  if logLevel >= minLevel
    then do
      today <- currentDay
      time <- currentTime
      let message =
            show today ++
            " " ++
            time ++
            " [" ++
            show (confMinLevel сonf) ++
            "] " ++ "[" ++ show logLevel ++ "] " ++ T.unpack text
      System.IO.hPutStrLn (confFileHandle сonf) message
      System.IO.hFlush (confFileHandle сonf)
    else pure ()
```
тут например явно `when` нужно использовать и hlint говорит об этом

**Comment by polina-nn** [comment]
Hlint мне про ошибки не говорит...

**Comment by pavelzarubin** [comment]
![Снимок экрана от 2023-04-27 06-28-52](https://user-images.githubusercontent.com/98732727/234752357-30ecde53-0c38-4c8c-bc5b-a07fb1881c0b.png)

**Comment by polina-nn** [comment]
Доброе утро! Да, у меня был старый hlint. Поправила.
https://github.com/polina-nn/news/pull/new/18_hlint
