### ISSUE TITLE
Id

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#19]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/Types/DataTypes.hs#L152-L157

Смотри, здесь в качестве ID используется синоним типа. Давай переделаем. Сделаем ID, который будет привязан к конкретной сущности. Выглядеть будет как то так.
```haskell
newtype Id a = Id {getId :: Int}
```
тем самым это будут те же `Int`, но ты не сможешь их перепутать, что сделает это куда безопаснее.

**Comment by polina-nn** [comment]
Как я понимаю,  по аналогии есть переделать все эти типы, так как я даже пока писала запуталась в фильтрации с датами, лимит с офсетом путала...
type DayAt = TIME.Day
type DayUntil = TIME.Day
type DaySince = TIME.Day
-- | type Limit -  maximum array length per get request
type Limit = Int
-- | type Offset - offset from the beginning of  get response array
type Offset = Int
-- | type Id - id for user, category, image
type Id = Int
-- | type Name - name for user, category, image, news
type Name = T.Text

-- | type Path - path for category (e.g.  1.23.8.1)
type Path = String
type URI = String

Если переделывать сразу все, то опять весь проект покраснеет и будет неудобно смотреть. Как лучше?

**Comment by pavelzarubin** [comment]
Вообще, на мой взгляд лучше использовать newtype в таких случаях, так как он действительно спасет от путаницы. Можешь конечно оставить как есть, но сама говоришь, что уже путалась.

**Comment by pavelzarubin** [comment]
Чтобы весь проект не был красным, ты его отформатируй весь, а потом вноси правки.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/19_use_newtype
Здравствуй!
1. Добавила еще миграции (04.sql), так как после удаления siquence у меня начанается опять нумерация с 1, ну и соответственно возникает ошибка при добавлении новости или картинки. Очевидно, что данная миграция будет корректной только в случае, если новости из сервера не удалялись и нумерация начиналась 1. В других случаях id_news у старых новостей поплывет.  Такой вариант для нашего сервера пойдет?
2. Добавила newtype для id сущностей, limit, offset, filter
3. Заменила concat на <> и .<
