### ISSUE TITLE
Оформление.

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#2]
Я не знаю какой у тебя форматтер, но ormolu файлы меняет. Есть варнинги от hlint. Есть лишние комментарии.

**Comment by pavelzarubin** [comment]
Если пользуешься VSCode поставь `Code Spell Checker` расширение, имена функций чтобы назывались правильно.

**Comment by pavelzarubin** [comment]
https://github.com/polina-nn/news/blob/c6c0b6d15155c6c7a0bf7b33fa6046d6c6131182/src/Types/DataTypes.hs#L218-L223

в Haskell мы используем `camelCase`

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/2_omoru_camelCase_hlint

**Comment by pavelzarubin** [comment]
Какая у тебя версия ормолу, так как мой форматтер до сих пор реагирует?

**Comment by pavelzarubin** [comment]
У меня ormolu до сих пор вносит справления? у тебя какая версия используется. Я попробовал несколько, 0.1.4.1, 0.3_ и последнюю, все три вносят изменения

**Comment by polina-nn** [comment]
Привет, я еще та курица. Я умудрилась после  ormolu, прогнать через hindent.😂
Я сделала исправления по ишью про базу данных, завтра выложу и перед этим прогоню только через ormolu.
Надеюсь наши варианты будут теперь совпадать. Я на дежурстве, не могу глянуть версию ormolu….

  
>Вторник, 27 декабря 2022, 9:35 +03:00 от pavelzarubin ***@***.***>:
> 
> 
>У меня ormolu до сих пор вносит справления? у тебя какая версия используется. Я попробовал несколько, 0.1.4.1, 0.3_ и последнюю, все три вносят изменения
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you modified the open/close state. Message ID:  <polina-nn/news/issues/2/1365650007 @ github . com> 
 
 
--
Полина Морозова
