### ISSUE TITLE
Конфиг

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#20]
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/Config.hs#L95-L117

Вместо того, чтобы бросать ошибку, о том что конфиг неверный, можно сделать так, чтобы выдавалась ошибка какого поля не хватает.

**Comment by roman-bodavskiy** [comment]
Вообще с конфигом довольно странная логика.  Можно от `Maybe` типов (`MaybeDbConfig` и других) избавиться, вместо этого сразу выкидывать ошибку если какого-то поля нету (с названием поля). А если все поля на месте, то собирать нормальные конфиги (`DbConfig` и прочие)

**Comment by polina-nn** [comment]
Здравствуйте!
https://github.com/polina-nn/news/pull/new/20_config
1. Доработала модуль Types.ExceptionTypes  дополнив тип serverException. Сервер не заработает если нет конфига, или какое-либо поле не читается, если нет соединения с БД, или если файл миграций с проблемами.
Может я что-то ещё должна включить в этот тип?
2. Соответственно поправила логику работы с конфигом, там теперь возникают serverException.
