### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by roman-bodavskiy** [polina-nn/news#23]
Привет. Меня зовут Роман, я буду проводить ревью вместе с Пашей
Первое что бросилось в глаза, это строка длиной в 1000 символов, не очень удобочитаемо)

https://github.com/polina-nn/news/blob/master/src/Types/ApiTypes.hs#L31

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/23_break_long_lines
