### ISSUE TITLE
Использование нетотальных функций

### ISSUE THREAD

**Issue by roman-bodavskiy** [polina-nn/news#28]
Использование нетотальных функций `head`, `read` запрещено, разве что кроме тестов. Лучше использовать их безопасные аналоги `listToMaybe`, `readEither` и выкидывать ошибку если что-то пошло не так

**Comment by polina-nn** [comment]
Здравствуй!
https://github.com/polina-nn/news/pull/new/28_untotal_functions
Поправила! Убрала read, из readFile  выбрасывается ошибка. 
Head вообще не осталось.
