### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#3]
Нет обработки ошибки, когда соединение с базой потеряно.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/3_dBConnect
Я уже голову сломала как правильно сделать:
1. В модуле DbException определила две функции: одна проверки соединения с базой во время запуска сервера (использую только в DbServices.initConnPool), вторая работает в каждом эндпойте перед запросом в базу, при этом она возвращает ErrorTypes.SQLRequestError (500 код) . Соответственно в каждом запросе я закрываю соединение. 
2. Потом я поняла, что данная схема не работает для запросов с авторизацией. И в module Server в функцию myAuthCheck, я добавила проверку на соединение с базой. Ну и при запросах с авторизацией myAuthCheck может 
вернуть Unauthorized, что видется пользователю как 403 ошибка....
Подскажи, как заставить сервант возвращать 500 ошибку для запросов с авторизацией... Читала документацию, никак не соображу.

**Comment by pavelzarubin** [comment]
Ну он тебе все правильно возвращает, ты же используешь BasicAuthResult для аутентификации. Если хочешь свой код ошибки отправлять, то нужно свой тип придумать и там уже прописать, что да как возвращаться будет.

**Comment by polina-nn** [comment]
Читать после отпуска!!!  "то нужно свой тип придумать и там уже прописать, что да как возвращаться будет." - не могу понять где это можно придумать в рамках Basic Authentication.
https://docs.servant.dev/en/stable/tutorial/Authentication.html#basic-authentication
Как я понимаю при Basic Authentication я могу вернуть только 4 заданных вида ошибки, если я хочу придумать свой тип ошибки, то мне нужно уже использовать Generalized Authentication...(https://docs.servant.dev/en/stable/tutorial/Authentication.html#generalized-authentication) и много чего переделывать.

**Comment by pavelzarubin** [comment]
Можешь так. Можешь просто передавать в каждом запросе заголовки с логином и паролем и проверять.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/3_exceptT_dbConnect
Доброе утро, Павел!
1. Я так и не поняла,  как используя basic auth ( по техническому заданию на сервер), можно вернуть error 500 для запросов с авторизацией. 
https://github.com/polina-nn/news/blob/3_exceptT_dbConnect/src/Server.hs
Как я поняла, запрос с авторизацией останавливается при отсутствии соединенения на функции myAuthCheck, а оттуда  в app :: News.Handle IO -> POOL.Pool SQL.Connection -> Application, и как отсюда выбросить error 500, не понятно.
2. Я попыталась сделать два эндпойта: 
https://github.com/polina-nn/news/blob/master/src/EndPoints/AddOneImage.hs
https://github.com/polina-nn/news/blob/master/src/EndPoints/GetOneImage.hs
Как я поняла, мне нужно открывать и закрывать  соединение в каждой функции, где есть
работа с SQL.Connection и выброс EX.throwE, иначе у меня останутся открытые соединения ( в текущей версии нужно добавить закрытие соединения в функцию myAuthCheck).
3. В эндпойтах с авторизацией и без нее все равно вызываю tryRequestConnectDb, так как при смене вида авторизации я уже могу быть залогинена, и тогда при разрыве соединения  выйдет 500 ошибка из эндпойта. Но basic auth я при каждом запросе шлю логин и пароль, поэтому до эндпойта не дохожу и вылетаю по myAuthCheck.
Короче, как получить error 500 в серванте при basic auth , подскажи, пожалуйста....

**Comment by pavelzarubin** [comment]
1. По поводу BasicAuth я уже писал. Если хочешь чтобы свои ошибки бросались, то не нужно использовать BasicAuth. Тебе нужно написать собственный аналог BasicAuth для этого, либо аутентификацию производить иначе.
2. Закрывать соединения не нужно, ты же используешь пул соединений, они закрываются автоматически, когда не используются. При восстановлении базы, соединения также заработают. Если ты будешь их закрывать принудительно, то у тебя все рухнет, так как это происходит не в пуле.
3.Ответил в первом пункте.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/3_unhappy_pool
Добрый вечер!
Не могу понять, почему не работают даже миграции...
Server.run
Переделала функцию DbServices.initConnPool с использованием 
POOL.createPool (SQL.connectPostgreSQL $ SQL.postgreSQLConnectionString (url h)).... и все

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/3_happy_pool
теперь пул работает, осталось избавиться от "что-то пошло не так"

**Comment by polina-nn** [comment]
От "что-то пошло не так" избавилась.
Можно смотреть (3_happy_pool)!
Если включаю сервер с выключенной базой, то на этапе миграции Exception: ExitFailure 1. Ну или если результат миграции ErrorMessage, то тоже Exception: ExitFailure 1.
