### ISSUE TITLE
Обработка ошибок

### ISSUE THREAD

**Issue by roman-bodavskiy** [polina-nn/news#34]
Обработка ошибок выглядит чересчур громоздкой и отвлекает от основного кода. Вот например

```
      liftIO $
        Logger.logError
          (News.hLogHandle h)
          ( "ERROR "
              .< ErrorTypes.InvalidCategoryIdAddEditNews
                ( ErrorTypes.InvalidContent "checkCategoryId: BAD! Not exists category with id "
                )
          )
      EX.throwE $ ErrorTypes.InvalidCategoryIdAddEditNews $ ErrorTypes.InvalidContent []
```

Можно придумать какую-то обертку throwError, чтобы логгирование было уже внутри:

```
 throwError h . ErrorTypes.InvalidCategoryIdAddEditNews . ErrorTypes.InvalidContent $
   "checkImageFileExist: BAD!  File: does not exist (No such file or directory) "
```

Может быть даже можно убрать один конструктор `ErrorTypes.InvalidContent`, не уверен что он несет какую-то пользу.

**Comment by roman-bodavskiy** [comment]
Также я протестировал твои запросы, пользователю не сообщается никакое сообщение об ошибке:

```
roman@Roman-PC:~/Projects/Morozova/server/news$ sh _scripts/5_AddOneNews.sh
HTTP/1.1 400 "400 Bad Request"
Transfer-Encoding: chunked
Date: Mon, 03 Apr 2023 12:04:24 GMT
Server: Warp/3.3.21

curl: (6) Could not resolve host: \
roman@Roman-PC:~/Projects/Morozova/server/news$ sh _scripts/5_AddOneNews.sh
HTTP/1.1 400 "400 Bad Request"
Transfer-Encoding: chunked
Date: Mon, 03 Apr 2023 12:04:53 GMT
Server: Warp/3.3.21
```

Когда код ошибки 400, нужно сообщить пользователю, что именно не так в его запросе. Когда код ошибки 500 (Internal Server Error), то пользователю не нужно показывать сообщение, только писать его в логи; и т. д.

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/34_handle_error
Добавила развернутые ответы на 400 ошибку
Переделала обработку ошибок.
