### ISSUE TITLE
Категории

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#4]
А зачем такой сложный алгоритм для категорий? Почему бы при создании новой категории не передавать id родителя? Переделывать не нужно, но странное как по мне решение.

**Comment by polina-nn** [comment]
Да, мне пришлось выбрать схему Materialized Path и возиться с пафами (при добавлении и редактировании категорий), так как у меня не получилось реализовать представлении категорий как Adjacency List - я запуталась в розовых деревьях... Или я что-то недопонимаю пока в этом.

**Comment by pavelzarubin** [comment]
Я не использовал никаких моделей. (я даже про них не читал). Я написал функцию внутри базы, которая собирала список категорий по parent_id. И на выходе получался список категорий, он даже по идее был сортирован по вложенности. Просто у тебя постоянно переписываются пути вложенности, что очень неудобно. Да и по сути у каждой категории есть только один родитель, а так придется вычислять сложный путь для каждой категории.

**Comment by polina-nn** [comment]
Добрый день! Переделала работу с категориями на "parent id"
 https://github.com/polina-nn/news/pull/new/4_category
Можно открыть ишью на переделку handle, чтобы все это тестировать, теперь много логики стало в sql запросах...Не совсем понимаю как написать тесты
