### ISSUE TITLE
Нет доступа к файлу логов

### ISSUE THREAD

**Issue by roman-bodavskiy** [polina-nn/news#43]
Когда перезапускаешь сервер второй раз, нет доступа к файлу логов, и приходится его удалять

`Exception: logs: openFile: resource busy (file is locked)`
возможно из-за того, что нужно закрывать файл после каждого использования

**Comment by roman-bodavskiy** [comment]
у тебя вроде в ридми это даже написано

**Comment by polina-nn** [comment]
Добрый день! Добавила Control.Exception.Safe.finally в runServer
https://github.com/polina-nn/news/pull/new/43_logs_locked
