### ISSUE TITLE
Deriving

### ISSUE THREAD

**Issue by pavelzarubin** [polina-nn/news#5]
https://github.com/polina-nn/news/blob/c6c0b6d15155c6c7a0bf7b33fa6046d6c6131182/src/Types/DataTypes.hs#L124
можно использовать расширение `DeriveAnyClass`, и поместить в `deriving`

**Comment by polina-nn** [comment]
https://github.com/polina-nn/news/pull/new/5_add_DeriveAnyClass

**Comment by polina-nn** [comment]
Простейшее исправление,  поэтому закрыла ишью сама.

**Comment by pavelzarubin** [comment]
А вот и зря
https://github.com/polina-nn/news/blob/805447a13cea1bb97fbf977c85472a0541ee8e2c/src/Types/DataTypes.hs#L104-L116

**Comment by polina-nn** [comment]
исправила
